### ISSUE TITLE
prayer time not working

### ISSUE THREAD

**Issue by yemencafe** [Muhammed-Ayad/Balgho-Convey#6]
prayers times not working
says (please connect to internet)

**Comment by Muhammed-Ayad** [comment]
I will work on it inshallah

**Comment by salamaEnigma** [comment]
@yemencafe Prayer times has been fixed in the branch **`new-release`**

**Comment by yemencafe** [comment]
> @yemencafe Prayer times has been fixed in the branch **`new-release`**

ma sha' allah
nice work
tested and working fine.
